### ISSUE TITLE
Use data driven statistics from ballchasing replays

### ISSUE THREAD

**Issue by deweller** [Davek84/MatchOdds#1]
I'd like to see match odds calculated according to data from a large group of replays.

My idea is this:

1. Download a few thousand replays from ballchasing.com.
2. Build lookup tables based on MMR difference, goal difference and time remaining.
3. Modify the plugin to look up this data from the table.

Is this something you are interested in seeing added to this plugin?  If so, I'm interested in building this and submitting it as a pull request.

**Comment by Davek84** [comment]
This is a little beyond my technical abilities so feel free to see if you can bundle something like that in!
