### ISSUE TITLE
Odds not showing up at all

### ISSUE THREAD

**Issue by silembir** [Davek84/MatchOdds#3]
Hi,

Just installed MatchOdds and not seeing any sign of the plugin when playing.  I made sure it is enabled within the BakkesMod settings and even restarted the game to be sure.  I tried multiple game modes, both competitive and casual.  Thanks.

**Comment by Davek84** [comment]
Ensure the 'Show MMR on scoreboard' option is enabled in the 'Ranked' tab
of BakkesMod

**Comment by silembir** [comment]
That fixed it, thanks!
