### ISSUE TITLE
Question: Not showing any odds with bots

### ISSUE THREAD

**Issue by sout12** [Davek84/MatchOdds#4]
So I am not sure if this is an issue more just like a question because I know the odds are based off of MMR, I assume this doesn't work for bots correct? I tested a few exhibition matches and didn't see the overlay.

**Comment by Davek84** [comment]
Yeah it doesn't work with bots due to no MMR.  _(You should be 100% winning all bot matches, so maybe I'll hard code something in the future! 😄)_

**Comment by sout12** [comment]
> Yeah it doesn't work with bots due to no MMR. _(You should be 100% winning all bot matches, so maybe I'll hard code something in the future! 😄)_

Gotcha cool, I wasn't sure if it there was a way to predict odds based on player scores in game, thanks a lot for the info :)
